netlify/remix-compute

README.md, packages/edge-demo-site/README.md, packages/remix-edge-adapter/README.md
Some small cleanup in the README files.
- Related Issue #17
- Closes #
Ignore the `deploy/netlify — Deploy Preview failed.`. It's something I'm trying to remove from the repository checks.
can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or
something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
=> chore: readme cleanup

packages/remix-edge-adapter/package.json, packages/remix-runtime/package.json
Sets the publish config to publish scoped packages as public. We did this manually yesterday for the first release, so it shouldn't change, but this ensures these always publish as public.
- Related Issue #29
- Closes #
=> chore: set publish access to public for scoped packages

package-lock.json, package.json, packages/edge-demo-site/app/entry.server.tsx
Updates the Netlify Edge Functions demo site to use `renderReadableStream`. I checked in with the Remix team after Wes opened #50. Most other templates for edge in the Remix repo use `renderToString` but Jacob recommended to go with `renderReadableStream` instead of `renderToString`.
Thanks again for the feedback @jacob-ebey and @wesbos!
- Related Issues:
- #16
- #50
- Closes #
The deploy preview is all green and when you open the site, it loads up.
**A picture of a cute animal (not …
=> chore: update demo site to use renderToReadableStream

package-lock.json, packages/edge-demo-site/package.json, packages/remix-edge-adapter/src/defaultRemixConfig.ts
See https://github.com/remix-run/remix/pull/6650
=> feat(remix-edge-adapter)!: update default config

package.json, packages/edge-demo-site/netlify.toml
Configures the netlify configuration to be in line with the new monorepo support
disregard the build failures for the hydrogen remix site in the PR checks.
- Closes #144
All the checks should be green. Nothing to test manually.
=> chore: setup netlify config for new monorepo support

package.json, packages/demo-site/netlify.toml, packages/demo-site/remix.config.js
Fixes the Remix serverless demo site to support the improved monorepo support. Fixing this will help get the checks in #126 green.
The Hydrogen demo site and Remix edge demo site checks will fail for now as #126 is not merged yet and I'm currently fixing the other demo site in #165.
- Related PR #126
The Remix serverless site should build and the E2E tests pass for it.
=> chore: fixed build for remix serverless demo site

packages/edge-demo-site/remix.config.js
The edge demo site currently builds incorrectly due to the improved monorepo support. The hack I had in place is no longer required.
The Hydrogen demo site and Remix Serverless (demo site) checks will fail for now as #126 is not merged yet and I'm currently fixing the other demo site (remix-serverless).
- Related PR #126
- Related to issue https://github.com/netlify/pod-ecosystem-frameworks/issues/385
Everything goes green.
=> chore: fixed serverBuildPath for edge demo site for new monorepo support

packages/remix-adapter/src/plugin.ts, packages/remix-edge-adapter/src/plugin.ts
On Windows, run `ntl build --offline` on `demos/vite-functions` or `demos/vite-edge` and you will receive some version of the following error:
```
There was an error when loading the '...uildserverserver.js' npm module.
Support for npm modules in edge functions is an experimental feature. 
Refer to https://ntl.fyi/edge-functions-npm for more information.
```
This happens because `export { default } from "..\..\build\server\server.js";` is generated at the top of `demos/vite-functions/.netlify/functions-internal/remix-server.mjs`. The backslashes are then read as escape characters, hence the `'...uildserverserver.js'` with missing characters in the error message.
The fix is to convert the path to posix before generating the file to create the following output instead:
```
export { default …
```
=> Fix import path in function when building on Windows

packages/remix-edge-adapter/src/plugin.ts
Adds a default exclusion so that edge SSR doesn't run for paths under `/.netlify`. I'm going to follow up with an option to add custom paths, but that'll need docs so it will come later.
=> fix(remix-edge-adapter): exclude /.netlify paths from edge function

CONTRIBUTING.md, packages/remix-adapter/README.md, packages/remix-edge-adapter/README.md
- `CONTRIBUTING.md` had incorrect dev instructions and copypasta
- the `remix-edge-adapter` README was misleading
- the `remix-adapter` README was a generic Remix project README
These could/should be improved further but I just wanted to fix these glaring issues first.
N/A
=> docs: fix a few readme errors

package.json, packages/remix-adapter/package.json, packages/remix-edge-adapter/package.json, packages/remix-runtime/package.json
Dependent Remix versions already need Node v18
CC/ @ascorbic @nickytonline
=> fix: update `engines` field

packages/remix-edge-adapter/package.json
Introduced in https://github.com/netlify/remix-compute/pull/212. Not yet released.
=> chore: fix duplicate `engines` in `package.json`

renovate.json, renovate.json5
This configures Renovate to open bump PRs for Remix dependencies in test fixture sites, including unstable releases. This acts as an automated mechanism to run our test suites against Remix releases as soon as possible.
In a later PR, we'll add a notification mechanism for failures on such PRs.
FRA-525
I've [validated the config file syntax](https://docs.renovatebot.com/config-validation/).
We've validated most of this already by testing this out in next-runtime-minimal.
We can't really QA this without merging to main.
See also:
- https://docs.renovatebot.com/configuration-options/#respectlatest
- https://docs.renovatebot.com/configuration-options/#ignoreunstable
- https://docs.renovatebot.com/configuration-options/#ignorepaths
- …
=> chore(renovate): configure @remix-run bumps in test fixtures

.github/workflows/failure-notifier.yml
In https://github.com/netlify/remix-compute/pull/355 we configured Renovate to open bump PRs for Remix dependencies within our test fixtures and in https://github.com/netlify/remix-compute/pull/348 we added some e2e tests.
This PR adds a workflow that creates an issue in this repo when one of these PRs fails. We'll separately configure an integration for all issues here to become tickets for our team's triage rotation. This ensures we are proactive about potential regressions caused by framework releases, even pre-releases.
This workflow seems convoluted as written but as far as I can tell this is as simple as I can make it due to various limitations 🤷🏼.
FRA-535
Unfortunately, for security reasons:
> Note: This event will only trigger a workflow run if the workflow file is on the default …
=> ci: add workflow to notify on Remix bump failures

.github/workflows/failure-notifier.yml
I couldn't quite figure out why, but the `check_suite` events weren't firing.
I couldn't use the `status` events, because those are only about the legacy(ish) Commit Status API, which is completely separate from the Checks API, which all GitHub Apps and all GitHub Actions use.
I preferred not to use the `workflow_run` events, because it requires explicitly listing the other workflows it depends on - it doesn't support listening to all workflow events. I didn't like the brittle action-at-a-distance created by needing to keep the full list of workflows in sync between this file and other config locations.
I couldn't trivially use the `pull_request` events, because there is no event that triggers when the PR (or HEAD commit) status(es) change(s) - i.e. at the time of the PR opening or being …
=> ci: fix Remix bump failure notifier workflow

tests/e2e/fixtures/edge-site/app/routes/cached-for-a-year.tsx, tests/e2e/fixtures/edge-site/app/routes/headers.tsx, tests/e2e/fixtures/edge-site/app/routes/middleware-header.tsx, tests/e2e/fixtures/edge-site/app/routes/stale-while-revalidate.tsx, tests/e2e/fixtures/edge-site/netlify/edge-functions/middleware-header.ts, tests/e2e/fixtures/edge-site/netlify/functions/purge-cdn.ts, tests/e2e/fixtures/serverless-site/app/routes/cached-for-a-year.tsx, tests/e2e/fixtures/serverless-site/app/routes/headers.tsx, tests/e2e/fixtures/serverless-site/app/routes/middleware-header.tsx, tests/e2e/fixtures/serverless-site/app/routes/stale-while-revalidate.tsx, tests/e2e/fixtures/serverless-site/netlify/edge-functions/middleware-header.ts, tests/e2e/fixtures/serverless-site/netlify/functions/purge-cdn.ts, tests/e2e/user-journeys.spec.ts
This adds user journey tests related to caching
Closes https://linear.app/netlify/issue/FRA-509/implement-remix-user-journey-tests-related-to-caching
Given | When | Then | Note
-- | -- | -- | --
loader returns custom Cache-Control: foo response header for A | load A | serves response with Cache-Control: foo header | Implemented
configured middleware via framework which sets custom Foo: bar response header for A | load A | serves response with Foo: bar header | Not applicable / not implemented
user-defined Netlify Edge Function middleware which sets custom Foo: bar response header for A | load A | serves response with Foo: bar header | Implemented
configured SWR=90 for A | load Await 5sload Await 86sload Await 5sload A* requires sticky CDN node targeting | serves response from origin …
=> test: add test asserting loader headers can be set on response

.github/workflows/e2e.yml, playwright.config.ts
Recently added User Journey / e2e tests proved to be quite flaky, so this attempts to remove at least some flakiness
- Seems like on-demand Deno installation that happen when using CLI (or probably `@netlify/build`) is quite flaky, so we will preinstall it in Github Action
- Seems like running single worker is more beneficial than trying to parallelize work into 4 workers - https://github.com/netlify/remix-compute/pull/375#discussion_r1628015921 has a bit more context on that
- Closes https://linear.app/netlify/issue/FRA-509/implement-remix-user-journey-tests-related-to-caching
ensures we can discuss the changes and get feedback from …
=> chore: deflake user journey tests

.github/.kodiak.toml
We have specific configuration for what Renovate should automerge, but then a separate Kodiak config that automerges based on another set of rules.
We only want to use Kodiak to auto-approve Renovate PRs.
N/A
We should see it stop merging unstable remix bump PRs
=> ci(kodiak): fix conflict between Kodiak and Renovate

.github/workflows/release-please.yml
We recently added a post-install script that requires Deno, so we need to install it in this workflow.
=> ci: fix release-please action

packages/remix-edge-adapter/package.json
We accidentally introduced a dependency on `deno` at site build time by including a command that uses `deno` in a post-install hook.
The intent was to run it before typechecking and before publishing, so including it in the build command instead works as well but won't run for users.
N/A
Delete `packages/remix-edge-adapter/{dist,deno.d.ts}`, run `pnpm run build:packages`, inspect output, run `pnpm run typecheck`. All looks good.
=> fix(deps): remove unintentional user dependency on `deno`

packages/remix-adapter/package.json, packages/remix-edge-adapter/package.json, packages/remix-runtime/package.json, packages/remix-runtime/src/index.ts, pnpm-lock.yaml
Some "unstable" functions and types were removed in https://github.com/remix-run/remix/pull/9893.
Since they were clearly named `unstable_` and Remix doesn't require major releases for changes to these, we'll do the same thing here.
We should probably just not export any `unstable_`e xports. Remix doesn't actually require that server runtime implementations export these: https://github.com/remix-run/remix/tree/main/packages/remix-server-runtime#readme.
Closes #458, which actually affects both Remix and Hydrogen.
N/A - just bumps remix dev dep and fixes type errors
=> fix: stop re-exporting exports removed in remix@2.12.0

docs/upgrading.md
I didn't even know this guide existed until recently. Let's make it more discoverable by linking to it here.
This is especially relevant now that React Router 7 has landed — with only Vite support.
=> docs: link to Vite migration guide

package.json, packages/remix-edge-adapter/src/vite/plugin.ts, pnpm-lock.yaml, tests/e2e/fixtures/classic-edge-site/app/routes/_index.tsx, tests/e2e/fixtures/edge-site/app/routes/cached-for-a-year.tsx, tests/e2e/fixtures/edge-site/app/routes/headers.tsx, tests/e2e/fixtures/edge-site/app/routes/stale-while-revalidate.tsx, tests/e2e/fixtures/react-router-serverless-site/app/routes/cached-for-a-year.tsx, tests/e2e/fixtures/react-router-serverless-site/app/routes/headers.tsx, tests/e2e/fixtures/react-router-serverless-site/app/routes/stale-while-revalidate.tsx, tests/e2e/fixtures/serverless-site/app/routes/cached-for-a-year.tsx, tests/e2e/fixtures/serverless-site/app/routes/headers.tsx, tests/e2e/fixtures/serverless-site/app/routes/stale-while-revalidate.tsx, tests/e2e/react-router-user-journeys.spec.ts, tests/e2e/remix-user-journeys.spec.ts, tests/e2e/support/deploy-to-netlify.ts
See https://github.com/pnpm/pnpm/issues/9029.
I ran this:
```sh
corepack prepare pnpm@8 --activate
corepack use pnpm@8
```
The lockfile rebuild upgraded typescript and revealed some errors, which I fixed.
And then this also contains a fix for an unrelated issue, which is that we were expecting certain debug response headers in some e2e tests but those were recently renamed. I was forced to fix both issues on the same PR, otherwise I could never get a green PR.
=> ci: fix pnpm integrity check

demos/vite-edge/package.json, demos/vite-functions/package.json, packages/remix-adapter/package.json, packages/remix-edge-adapter/package.json, packages/vite-plugin-react-router/package.json, pnpm-lock.yaml, tests/e2e/fixtures/edge-site/package.json, tests/e2e/fixtures/react-router-serverless-site/package.json, tests/e2e/fixtures/serverless-site/package.json
- Update peer dependencies of all packages to allow Vite 6
- Update demos and test fixtures to test against Vite 6
Fixes #496
=> fix(deps): support and test against Vite 6
